apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-trigger-dependency
      eventSourceName: webhook
      eventName: github
  triggers:
    - template:
        name: pipeline-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          parameters:
            - src:
                dependencyName: github-trigger-dependency
                dataKey: body
              dest: spec.arguments.parameters.0.value
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: pipeline-
              spec:
                entrypoint: pipeline
                serviceAccountName: user-workflow-sa
                arguments:
                  parameters:
                  - name: payload
                    value: "ERROR_GITHUB_PAYLOAD_EMPTY"
                templates:
                - name: pipeline
                  steps:
                  - - name: clone
                      template: clone
                      arguments:
                        parameters:
                        - name: payload
                          value: "{{workflow.parameters.payload}}"
                - name: clone
                  inputs:
                    parameters:
                    - name: payload
                  script:
                    image: public.ecr.aws/k7d0s6i7/public_system_container_ci:local
                    imagePullPolicy: Always
                    command: [bash]
                    source: |
                      set +x
                      set -e

                      PAYLOAD_FILE_PATH=$(mktemp)

                      cat >$PAYLOAD_FILE_PATH<<EOL
                      {{inputs.parameters.payload}}
                      EOL

                      echo '=============================================='
                      echo '        Original unprocessed payload          '
                      echo '=============================================='
                      cat $PAYLOAD_FILE_PATH

                      echo '=============================================='
                      echo '               Parse git params               '
                      echo '=============================================='
                      GIT_PARAMS_FILE_PATH=$(mktemp)
                      /pipeline/parse_git_params.sh $PAYLOAD_FILE_PATH $GIT_PARAMS_FILE_PATH


                      echo '=============================================='
                      echo '             Git clone + checkout             '
                      echo '=============================================='
                      CLONE_URL=$(grep "clone_url" $GIT_PARAMS_FILE_PATH | cut -d' ' -f2 )
                      REPO_FULL_NAME=$(grep "repo_full_name" $GIT_PARAMS_FILE_PATH | cut -d' ' -f2 )
                      REF=$(grep "ref" $GIT_PARAMS_FILE_PATH | cut -d' ' -f2 )
                      BRANCH_NAME=${REF##*/}
                      $REPO_PATH=$(PWD)/${REPO_FULL_NAME##*/}

                      git clone $CLONE_URL
                      cd $REPO_PATH && git checkout $BRANCH_NAME && cd ..

                      echo '=============================================='
                      echo '              Project contents                '
                      echo '=============================================='
                      ls $REPO_PATH
                      echo '=============================================='
                      echo '             Detect user services             '
                      echo '=============================================='
                      SERVICES_FOUND_FILE_PATH=$(mktemp)
                      /pipeline/detect_user_services.sh $REPO_PATH $SERVICES_FOUND_FILE_PATH

                      cat $SERVICES_FOUND_FILE_PATH

                      echo '=============================================='
                      echo '                 Build services                '
                      echo '=============================================='
                      echo '....PENDING....'
