apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: full
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:full-cnb"
  runImage:
    image: "paketobuildpacks/run:full-cnb"
