apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: builder
spec:
  serviceAccount: kpack-build-sa
  tag: rromanotero/builder
  stack:
    name: full
    kind: ClusterStack
  store:
    name: store
    kind: ClusterStore
  order:
  - group:
    - id: heroku/nodejs-engine
    - id: heroku/nodejs-yarn
    - id: heroku/nodejs-typescript
  - group:
    - id: heroku/nodejs-engine
    - id: heroku/nodejs-npm
    - id: heroku/nodejs-typescript
  - group:
    - id: heroku/nodejs-engine
    - id: heroku/nodejs-yarn
  - group:
    - id: heroku/nodejs-engine
    - id: heroku/nodejs-npm
  - group:
    - id: paketo-community/python
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/ruby
  - group:
    - id: paketo-buildpacks/go
