apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: my-python-builder
  namespace: default
spec:
  serviceAccount: kpack-build-sa
  tag: rromanotero/builder
  stack:
    name: full
    kind: ClusterStack
  store:
    name: python-store
    kind: ClusterStore
