apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: python
  namespace: default
spec:
  tag: rromanotero/image
  serviceAccount: kpack-build-sa
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://github.com/benwilcock/buildpacks-python-demo.git
      revision: e89f6a00f9b0b57e29f8df5bdcb10f358835c990
