apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: github
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: triggerPipeline
                serviceAccountName: user-workflow-sa
                arguments:
                  parameters:
                    - name: payload
                      # the value will get prepended by event payload from test-dep
                      value: hello world
                templates:
                  - name: triggerPipeline
                    inputs:
                      parameters:
                        - name: payload
                    resource:
                      action: create
                      manifest: |
                        apiVersion: argoproj.io/v1alpha1
                        kind: Workflow
                        metadata:
                          generateName: ci-pipeline-
                        spec:
                          arguments:
                            parameters:
                            - name: payload
                              value: {{inputs.parameters.payload}}
                          workflowTemplateRef:
                            name: ci-pipeline
                      successCondition: status.phase == Succeeded
                      failureCondition: status.phase in (Failed, Error)
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
