apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: github
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: pipeline
                serviceAccountName: user-workflow-sa
                arguments:
                  parameters:
                    - name: payload
                      # the value will get prepended by event payload from test-dep
                      value: hello world
                templates:
                  - name: pipeline
                    inputs:
                      parameters:
                        - name: payload
                    container:
                      image: debian:latest
                      command: [echo]
                      args: ["Pipeline triggered. Building repository {{inputs.parameters.payload.url}} at commit {{inputs.parameters.payload.head_commit.id}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
